### ISSUE TITLE
Non-existent one-to-one relationships

### ISSUE THREAD

**Issue by JohnMaguire** [tobscure/json-api#94]
Hi there,

I'm taking a look at [this part of the spec on relationships](http://jsonapi.org/format/#document-resource-object-related-resource-links).

> Resource linkage **MUST** be represented as one of the following:
>
>   * `null` for empty to-one relationships.
>   * an empty array (`[]`) for empty to-many relationships.
>   * a single [resource identifier](http://jsonapi.org/format/#document-resource-identifier-objects) object for non-empty to-one relationships.
>   * an array of [resource identifier objects](http://jsonapi.org/format/#document-resource-identifier-objects) for non-empty to-many relationships.

I'm not sure if my understanding is incorrect or not. My URL looks like this: `GET /v1/devices?include=group`

I have done this to get the "relationships" key to show up for all items:

```php
	public function group($device)
	{
		return new Relationship(
			$device['group_id'] ? new Resource([
				'id' => $device['group_id'],
				'name' => $device['group_name'],
			], new GroupSerializer) : null
		);
	}
```

Originally I tried to return null instead of a `Relationship`, but that removes the "relationships" block entirely. The only problem with the above solution is that it seems to only support "X-to-many" relationships. In other words, the response from the API looks like this:

```json
"relationships": {
    "group": []
}
````

I believe that in reality, I want it to look like this:

```json
"relationships": {
    "group": null
}
```

Is there any way to get this result? Thank you so much for this library! It's very flexible and useful.

**Comment by JohnMaguire** [comment]
I will note, some other things I tried:

1. Returning "null" from `group()` causes the "relationships" object to disappear. (I don't think this is desired behavior.)
2. I can't really specify "null" to `new Resource` as the serializer will not work.

**Comment by tobscure** [comment]
Thanks for the detailed report.

I've implemented a solution, which looks like this:

```php
    public function emptyToOne($device)
    {
        return new Relationship(new EmptyResource);
    }

    public function emptyToMany($device)
    {
        return new Relationship(new EmptyCollection);
    }
```

i.e. To return an empty to-one relationship, pass an EmptyResource instance as the Relationship data.
To return an empty to-many relationship, pass an EmptyCollection instance as the Relationship data. (Passing a Collection with an empty array will work too.)

Why necessitate an EmptyResource object rather than just passing null as the Relationship data? Because there are times where the user may not wish to include the `data` key in the relationship object at all, instead filling it with `links` or `meta` – null data value is reserved for this case.

**Comment by JohnMaguire** [comment]
👍 This works great, thank you!

**Comment by nubs** [comment]
Agreed - It worked exactly like expected.  Will there be a new version of tobscure/json-api released soon?
